name: docs

on:
  pull_request:
    branches: [master]
  push:
    paths:
      - '.github/**'
      - 'docs/**'
    branches: [master]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    env:
      working-directory: './docs'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Release to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_DEPLOY }}
          GIT_USER: git
        run: |
          git config --global user.email "kimlimjustin@gmail.com"
          git config --global user.name "kimlimjustin"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy