name: Compile TypeScript

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        steps:
        - uses: actions/checkout@v1
        - run: echo ${{matrix.TARGET}}

        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]
                node-version: [14.x, 15.x]
                include:
                    - os: windows-latest
                    - os: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: rm -rf node_modules && yarn install --frozen-lockfile
            - run: yarn compile
